spring.application.name=teamProject
# JSP View Resolver
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp



mybatis.configuration.map-underscore-to-camel-case=true
# 포트 (원하는 경우)
#server.port=8080